# 🎬 iromusic Recommender System

This notebook implements a movie recommender system using the data fetched from the iromusicapp.ir API.

## 0. Data Initialization
# This cell checks for existing data and fetches new data if needed

In [ ]:
#!pip install -e iromusic_client

Obtaining file:///c:/Users/disso/Project/iromusic_client/iromusic_client
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: requests>=2.28.0 in .\venv\Lib\site-packages (from iromusic_client==1.0.0) (2.32.5)
Requirement already satisfied: urllib3>=1.26.0 in .\venv\Lib\site-packages (from iromusic_client==1.0.0) (2.6.3)
Requirement already satisfied: click>=8.0.0 in .\venv\Lib\site-packages (from iromusic_client==1.0.0) (8.3.1)
Requirement already satisfied: colorama in .\venv\Lib\site-packages (from click>=8.0.0->iromusic_client==1.0.0) (0.4.6)
Requirement already satisfied: charset_normalizer<4,>=2 in .\venv\Lib\site-packages (from requests>=2.28.0->iromusic_client==1.0.0) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in .\venv\Lib\site-packages (from requests>=2.28.0->iromusic_client==1.0.0) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in .\venv\Lib\site-packages (from requests>=2.28.0->iromusic_client==1.0.0) (2026.2.25)
Building wheels for collected packages: iromusic_client
  Building editable for iromusic_client (pyproject.toml): started
  Building editable for iromusic_client (pyproject.toml): finished with status 'done'
  Created wheel for iromusic_client: filename=iromusic_client-1.0.0-0.editable-py3-none-any.whl size=10429 sha256=73c756f29dd46826f209c63f7c01e72a9b426685dbf1d13ee1d2f7645ef7f317
  Stored in directory: C:\Users\disso\AppData\Local\Temp\pip-ephem-wheel-cache-q6iol7i1\wheels\ec\43\9d\83bdf8caa6bacfa4de6658fb8225de6dbdc03fc235dedd302d
Successfully built iromusic_client
Installing collected packages: iromusic_client
Successfully installed iromusic_client-1.0.0

In [7]:
import os
import sys
from pathlib import Path
from iromusic_client.orchestrator import run_orchestrator

# Define output directory path
OUTPUT_DIR = Path("iromusic_client/output")

def fetch_data(endpoints=['music', 'movie'],content_types={'music': ['singles', 'albums'], 'movie': ['movies']}, max_pages=3000):
    """Fetch data using iromusic_client."""
    try:
        # Add src to path for import
        src_path = Path("iromusic_client/src")
        if str(src_path) not in sys.path:
            sys.path.insert(0, str(src_path))
        
        
        print("\n🚀 Starting data fetch...")
        print("   This may take a few minutes...")
        
        # Run orchestrator to fetch movie data
        run_orchestrator(
            endpoints,
            content_types,
            max_pages,
            output_dir=str(OUTPUT_DIR),
            output_level="normal",
        )
        
    except ImportError as e:
        print(f"\n❌ Import error: {e}")
        print("   Make sure iromusic_client is installed:")
        print("   pip install -e iromusic_client/src")
        raise
    except Exception as e:
        print(f"\n❌ Error fetching data: {e}")
        raise

In [ ]:
fetch_data()

2026-02-27 18:55:49,820 - iromusic_client.api_client - INFO - APIClient initialized
2026-02-27 18:55:49,822 - iromusic_client.file_handler - INFO - FileHandler initialized with output_dir: iromusic_client\output
2026-02-27 18:55:49,823 - iromusic_client.api_client - INFO - Fetching page 1: https://iromusicapp.ir/iroapi/music/posts?type=singles

🚀 Starting data fetch...
   This may take a few minutes...
ℹ ==================================================
ℹ Starting iromusic data fetch
ℹ ==================================================
→
Processing music/singles...
→ Fetching Music (singles)...

2026-02-27 18:55:51,100 - iromusic_client.api_client - INFO - Fetched 24 items from page 1
2026-02-27 18:55:51,101 - iromusic_client.api_client - INFO - Fetching page 2: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:55:51,692 - iromusic_client.api_client - INFO - Fetched 24 items from page 2
2026-02-27 18:55:51,693 - iromusic_client.api_client - INFO - Fetching page 3: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:55:52,455 - iromusic_client.api_client - INFO - Fetched 24 items from page 3
2026-02-27 18:55:52,456 - iromusic_client.api_client - INFO - Fetching page 4: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:55:52,997 - iromusic_client.api_client - INFO - Fetched 24 items from page 4
2026-02-27 18:55:52,999 - iromusic_client.api_client - INFO - Fetching page 5: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:55:53,617 - iromusic_client.api_client - INFO - Fetched 24 items from page 5
2026-02-27 18:55:53,619 - iromusic_client.api_client - INFO - Fetching page 6: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:55:54,259 - iromusic_client.api_client - INFO - Fetched 24 items from page 6
2026-02-27 18:55:54,260 - iromusic_client.api_client - INFO - Fetching page 7: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:55:54,960 - iromusic_client.api_client - INFO - Fetched 24 items from page 7
2026-02-27 18:55:54,962 - iromusic_client.api_client - INFO - Fetching page 8: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:55:55,770 - iromusic_client.api_client - INFO - Fetched 24 items from page 8
2026-02-27 18:55:55,771 - iromusic_client.api_client - INFO - Fetching page 9: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:55:56,285 - iromusic_client.api_client - INFO - Fetched 24 items from page 9
2026-02-27 18:55:56,287 - iromusic_client.api_client - INFO - Fetching page 10: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:55:56,988 - iromusic_client.api_client - INFO - Fetched 24 items from page 10
2026-02-27 18:55:56,990 - iromusic_client.api_client - INFO - Fetching page 11: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:55:57,634 - iromusic_client.api_client - INFO - Fetched 24 items from page 11
2026-02-27 18:55:57,635 - iromusic_client.api_client - INFO - Fetching page 12: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:55:58,257 - iromusic_client.api_client - INFO - Fetched 24 items from page 12
2026-02-27 18:55:58,259 - iromusic_client.api_client - INFO - Fetching page 13: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:55:58,884 - iromusic_client.api_client - INFO - Fetched 24 items from page 13
2026-02-27 18:55:58,885 - iromusic_client.api_client - INFO - Fetching page 14: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:55:59,453 - iromusic_client.api_client - INFO - Fetched 24 items from page 14
2026-02-27 18:55:59,454 - iromusic_client.api_client - INFO - Fetching page 15: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:00,006 - iromusic_client.api_client - INFO - Fetched 24 items from page 15
2026-02-27 18:56:00,007 - iromusic_client.api_client - INFO - Fetching page 16: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:00,811 - iromusic_client.api_client - INFO - Fetched 24 items from page 16
2026-02-27 18:56:00,812 - iromusic_client.api_client - INFO - Fetching page 17: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:01,694 - iromusic_client.api_client - INFO - Fetched 24 items from page 17
2026-02-27 18:56:01,695 - iromusic_client.api_client - INFO - Fetching page 18: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:02,423 - iromusic_client.api_client - INFO - Fetched 24 items from page 18
2026-02-27 18:56:02,425 - iromusic_client.api_client - INFO - Fetching page 19: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:03,122 - iromusic_client.api_client - INFO - Fetched 24 items from page 19
2026-02-27 18:56:03,124 - iromusic_client.api_client - INFO - Fetching page 20: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:03,829 - iromusic_client.api_client - INFO - Fetched 24 items from page 20
2026-02-27 18:56:03,830 - iromusic_client.api_client - INFO - Fetching page 21: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:04,543 - iromusic_client.api_client - INFO - Fetched 24 items from page 21
2026-02-27 18:56:04,544 - iromusic_client.api_client - INFO - Fetching page 22: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:05,167 - iromusic_client.api_client - INFO - Fetched 24 items from page 22
2026-02-27 18:56:05,168 - iromusic_client.api_client - INFO - Fetching page 23: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:05,755 - iromusic_client.api_client - INFO - Fetched 24 items from page 23
2026-02-27 18:56:05,757 - iromusic_client.api_client - INFO - Fetching page 24: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:06,291 - iromusic_client.api_client - INFO - Fetched 24 items from page 24
2026-02-27 18:56:06,293 - iromusic_client.api_client - INFO - Fetching page 25: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:06,909 - iromusic_client.api_client - INFO - Fetched 24 items from page 25
2026-02-27 18:56:06,910 - iromusic_client.api_client - INFO - Fetching page 26: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:07,580 - iromusic_client.api_client - INFO - Fetched 24 items from page 26
2026-02-27 18:56:07,581 - iromusic_client.api_client - INFO - Fetching page 27: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:08,127 - iromusic_client.api_client - INFO - Fetched 24 items from page 27
2026-02-27 18:56:08,129 - iromusic_client.api_client - INFO - Fetching page 28: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:08,817 - iromusic_client.api_client - INFO - Fetched 24 items from page 28
2026-02-27 18:56:08,818 - iromusic_client.api_client - INFO - Fetching page 29: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:09,575 - iromusic_client.api_client - INFO - Fetched 24 items from page 29
2026-02-27 18:56:09,577 - iromusic_client.api_client - INFO - Fetching page 30: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:10,311 - iromusic_client.api_client - INFO - Fetched 24 items from page 30
2026-02-27 18:56:10,313 - iromusic_client.api_client - INFO - Fetching page 31: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:10,904 - iromusic_client.api_client - INFO - Fetched 24 items from page 31
2026-02-27 18:56:10,905 - iromusic_client.api_client - INFO - Fetching page 32: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:11,456 - iromusic_client.api_client - INFO - Fetched 24 items from page 32
2026-02-27 18:56:11,457 - iromusic_client.api_client - INFO - Fetching page 33: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:12,147 - iromusic_client.api_client - INFO - Fetched 24 items from page 33
2026-02-27 18:56:12,149 - iromusic_client.api_client - INFO - Fetching page 34: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:12,920 - iromusic_client.api_client - INFO - Fetched 24 items from page 34
2026-02-27 18:56:12,921 - iromusic_client.api_client - INFO - Fetching page 35: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:13,621 - iromusic_client.api_client - INFO - Fetched 24 items from page 35
2026-02-27 18:56:13,623 - iromusic_client.api_client - INFO - Fetching page 36: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:14,271 - iromusic_client.api_client - INFO - Fetched 24 items from page 36
2026-02-27 18:56:14,273 - iromusic_client.api_client - INFO - Fetching page 37: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:14,819 - iromusic_client.api_client - INFO - Fetched 24 items from page 37
2026-02-27 18:56:14,820 - iromusic_client.api_client - INFO - Fetching page 38: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:15,432 - iromusic_client.api_client - INFO - Fetched 24 items from page 38
2026-02-27 18:56:15,434 - iromusic_client.api_client - INFO - Fetching page 39: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:15,944 - iromusic_client.api_client - INFO - Fetched 24 items from page 39
2026-02-27 18:56:15,946 - iromusic_client.api_client - INFO - Fetching page 40: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:16,692 - iromusic_client.api_client - INFO - Fetched 24 items from page 40
2026-02-27 18:56:16,694 - iromusic_client.api_client - INFO - Fetching page 41: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:17,270 - iromusic_client.api_client - INFO - Fetched 24 items from page 41
2026-02-27 18:56:17,272 - iromusic_client.api_client - INFO - Fetching page 42: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:17,816 - iromusic_client.api_client - INFO - Fetched 24 items from page 42
2026-02-27 18:56:17,817 - iromusic_client.api_client - INFO - Fetching page 43: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:18,372 - iromusic_client.api_client - INFO - Fetched 24 items from page 43
2026-02-27 18:56:18,373 - iromusic_client.api_client - INFO - Fetching page 44: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:18,897 - iromusic_client.api_client - INFO - Fetched 24 items from page 44
2026-02-27 18:56:18,899 - iromusic_client.api_client - INFO - Fetching page 45: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:19,512 - iromusic_client.api_client - INFO - Fetched 24 items from page 45
2026-02-27 18:56:19,513 - iromusic_client.api_client - INFO - Fetching page 46: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:20,137 - iromusic_client.api_client - INFO - Fetched 24 items from page 46
2026-02-27 18:56:20,139 - iromusic_client.api_client - INFO - Fetching page 47: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:20,752 - iromusic_client.api_client - INFO - Fetched 24 items from page 47
2026-02-27 18:56:20,753 - iromusic_client.api_client - INFO - Fetching page 48: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:21,502 - iromusic_client.api_client - INFO - Fetched 24 items from page 48
2026-02-27 18:56:21,503 - iromusic_client.api_client - INFO - Fetching page 49: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:22,184 - iromusic_client.api_client - INFO - Fetched 24 items from page 49
2026-02-27 18:56:22,185 - iromusic_client.api_client - INFO - Fetching page 50: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:22,929 - iromusic_client.api_client - INFO - Fetched 24 items from page 50
2026-02-27 18:56:22,930 - iromusic_client.api_client - INFO - Fetching page 51: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:23,597 - iromusic_client.api_client - INFO - Fetched 24 items from page 51
2026-02-27 18:56:23,599 - iromusic_client.api_client - INFO - Fetching page 52: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:24,144 - iromusic_client.api_client - INFO - Fetched 24 items from page 52
2026-02-27 18:56:24,146 - iromusic_client.api_client - INFO - Fetching page 53: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:24,690 - iromusic_client.api_client - INFO - Fetched 24 items from page 53
2026-02-27 18:56:24,692 - iromusic_client.api_client - INFO - Fetching page 54: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:25,383 - iromusic_client.api_client - INFO - Fetched 24 items from page 54
2026-02-27 18:56:25,384 - iromusic_client.api_client - INFO - Fetching page 55: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:26,010 - iromusic_client.api_client - INFO - Fetched 24 items from page 55
2026-02-27 18:56:26,012 - iromusic_client.api_client - INFO - Fetching page 56: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:26,674 - iromusic_client.api_client - INFO - Fetched 24 items from page 56
2026-02-27 18:56:26,676 - iromusic_client.api_client - INFO - Fetching page 57: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:27,564 - iromusic_client.api_client - INFO - Fetched 24 items from page 57
2026-02-27 18:56:27,565 - iromusic_client.api_client - INFO - Fetching page 58: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:28,227 - iromusic_client.api_client - INFO - Fetched 24 items from page 58
2026-02-27 18:56:28,229 - iromusic_client.api_client - INFO - Fetching page 59: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:28,884 - iromusic_client.api_client - INFO - Fetched 24 items from page 59
2026-02-27 18:56:28,885 - iromusic_client.api_client - INFO - Fetching page 60: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:29,507 - iromusic_client.api_client - INFO - Fetched 24 items from page 60
2026-02-27 18:56:29,509 - iromusic_client.api_client - INFO - Fetching page 61: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:30,080 - iromusic_client.api_client - INFO - Fetched 24 items from page 61
2026-02-27 18:56:30,081 - iromusic_client.api_client - INFO - Fetching page 62: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:30,683 - iromusic_client.api_client - INFO - Fetched 24 items from page 62
2026-02-27 18:56:30,684 - iromusic_client.api_client - INFO - Fetching page 63: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:31,291 - iromusic_client.api_client - INFO - Fetched 24 items from page 63
2026-02-27 18:56:31,293 - iromusic_client.api_client - INFO - Fetching page 64: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:31,881 - iromusic_client.api_client - INFO - Fetched 24 items from page 64
2026-02-27 18:56:31,882 - iromusic_client.api_client - INFO - Fetching page 65: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:32,566 - iromusic_client.api_client - INFO - Fetched 24 items from page 65
2026-02-27 18:56:32,567 - iromusic_client.api_client - INFO - Fetching page 66: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:33,235 - iromusic_client.api_client - INFO - Fetched 24 items from page 66
2026-02-27 18:56:33,237 - iromusic_client.api_client - INFO - Fetching page 67: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:33,776 - iromusic_client.api_client - INFO - Fetched 24 items from page 67
2026-02-27 18:56:33,777 - iromusic_client.api_client - INFO - Fetching page 68: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:34,576 - iromusic_client.api_client - INFO - Fetched 24 items from page 68
2026-02-27 18:56:34,578 - iromusic_client.api_client - INFO - Fetching page 69: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:35,249 - iromusic_client.api_client - INFO - Fetched 24 items from page 69
2026-02-27 18:56:35,251 - iromusic_client.api_client - INFO - Fetching page 70: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:35,967 - iromusic_client.api_client - INFO - Fetched 24 items from page 70
2026-02-27 18:56:35,968 - iromusic_client.api_client - INFO - Fetching page 71: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:36,631 - iromusic_client.api_client - INFO - Fetched 24 items from page 71
2026-02-27 18:56:36,633 - iromusic_client.api_client - INFO - Fetching page 72: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:37,277 - iromusic_client.api_client - INFO - Fetched 24 items from page 72
2026-02-27 18:56:37,278 - iromusic_client.api_client - INFO - Fetching page 73: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:37,944 - iromusic_client.api_client - INFO - Fetched 24 items from page 73
2026-02-27 18:56:37,945 - iromusic_client.api_client - INFO - Fetching page 74: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:38,664 - iromusic_client.api_client - INFO - Fetched 24 items from page 74
2026-02-27 18:56:38,666 - iromusic_client.api_client - INFO - Fetching page 75: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:39,319 - iromusic_client.api_client - INFO - Fetched 24 items from page 75
2026-02-27 18:56:39,320 - iromusic_client.api_client - INFO - Fetching page 76: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:39,963 - iromusic_client.api_client - INFO - Fetched 24 items from page 76
2026-02-27 18:56:39,965 - iromusic_client.api_client - INFO - Fetching page 77: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:40,634 - iromusic_client.api_client - INFO - Fetched 24 items from page 77
2026-02-27 18:56:40,635 - iromusic_client.api_client - INFO - Fetching page 78: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:41,161 - iromusic_client.api_client - INFO - Fetched 24 items from page 78
2026-02-27 18:56:41,162 - iromusic_client.api_client - INFO - Fetching page 79: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:41,874 - iromusic_client.api_client - INFO - Fetched 24 items from page 79
2026-02-27 18:56:41,876 - iromusic_client.api_client - INFO - Fetching page 80: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:42,429 - iromusic_client.api_client - INFO - Fetched 24 items from page 80
2026-02-27 18:56:42,431 - iromusic_client.api_client - INFO - Fetching page 81: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:43,107 - iromusic_client.api_client - INFO - Fetched 24 items from page 81
2026-02-27 18:56:43,108 - iromusic_client.api_client - INFO - Fetching page 82: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:43,796 - iromusic_client.api_client - INFO - Fetched 24 items from page 82
2026-02-27 18:56:43,797 - iromusic_client.api_client - INFO - Fetching page 83: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:44,510 - iromusic_client.api_client - INFO - Fetched 24 items from page 83
2026-02-27 18:56:44,512 - iromusic_client.api_client - INFO - Fetching page 84: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:45,283 - iromusic_client.api_client - INFO - Fetched 24 items from page 84
2026-02-27 18:56:45,285 - iromusic_client.api_client - INFO - Fetching page 85: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:45,936 - iromusic_client.api_client - INFO - Fetched 24 items from page 85
2026-02-27 18:56:45,937 - iromusic_client.api_client - INFO - Fetching page 86: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:46,517 - iromusic_client.api_client - INFO - Fetched 24 items from page 86
2026-02-27 18:56:46,518 - iromusic_client.api_client - INFO - Fetching page 87: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:47,034 - iromusic_client.api_client - INFO - Fetched 24 items from page 87
2026-02-27 18:56:47,035 - iromusic_client.api_client - INFO - Fetching page 88: https://iromusicapp.ir/iroapi/music/posts?type=singles
2026-02-27 18:56:47,568 - iromusic_client.api_client - INFO - Fetched 24 items from page 88
2026-02-27 18:56:47,569 - iromusic_client.api_client - INFO - Fetching page 89: https://iromusicapp.ir/iroapi/music/posts?type=singles

## 1. Data Loading

In [3]:
# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import json
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)
plt.style.use('seaborn-v0_8-whitegrid')

In [5]:
# Load data
DATA_PATH = Path("iromusic_client//output//2026//02//26//movie")
json_files = list(DATA_PATH.glob("*.json"))
latest_file = max(json_files, key=lambda p: p.stat().st_mtime)
print(f"Loading: {latest_file.name}")

with open(latest_file, 'r', encoding='utf-8') as f:
    movie_data = json.load(f)

df = pd.DataFrame(movie_data)
print(f"Dataset: {df.shape[0]} movies")

Loading: movie_movies_2026-02-26_18-12-13.json
Dataset: 65 movies

In [7]:
df

,id,type,slug,englishTitle,alternateTitle,year,imageUrl,genres,rated,imdbRating,views,likes,updatedAt,updateTime,created_at,updated_at,processed_at
0,25114,movies,roshan-1398,Roshan,روشن,1398,https://iroapp.ir//archive/movies/per/1404/r/r...,"[{'title': 'Drama', 'slug': 'drama', 'titleFar...",+15,0,0,0,1404/12/7,2026-02-26T14:40:17.678Z,2026-02-26T18:12:13.015761,2026-02-26T18:12:13.015775,2026-02-26T18:12:13.015781
1,25092,movies,shelter-2026,Shelter,Shelter,2026,https://iroapp.ir//archive/movies/english/s/sh...,"[{'title': 'Thriller', 'slug': 'thriller', 'ti...",N/A,0,0,1,1404/12/7,2026-02-26T14:40:07.170Z,2026-02-26T18:12:13.015819,2026-02-26T18:12:13.015826,2026-02-26T18:12:13.015832
2,25113,movies,twisted-2026,Twisted,Twisted,2026,https://iroapp.ir//archive/movies/english/t/tw...,"[{'title': 'Horror', 'slug': 'horror', 'titleF...",R,4.6,0,0,1404/12/7,2026-02-26T14:33:35.357Z,2026-02-26T18:12:13.015860,2026-02-26T18:12:13.015864,2026-02-26T18:12:13.015869
3,25112,movies,firebreak-2026,Firebreak,Firebreak,2026,https://iroapp.ir//archive/movies/english/f/fi...,"[{'title': 'Drama', 'slug': 'drama', 'titleFar...",N/A,5.7,0,0,1404/12/7,2026-02-26T14:32:52.851Z,2026-02-26T18:12:13.015893,2026-02-26T18:12:13.015899,2026-02-26T18:12:13.015903
4,25111,movies,the-bluff-2025,The Bluff,The Bluff,2025,https://iroapp.ir//images/movie/t/the-bluff-20...,"[{'title': 'Drama', 'slug': 'drama', 'titleFar...",N/A,0,0,0,1404/12/7,2026-02-26T14:31:55.402Z,2026-02-26T18:12:13.015916,2026-02-26T18:12:13.015919,2026-02-26T18:12:13.015922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,25031,movies,bi-saro-seda-2024,Bi Saro Seda,بی سر و صدا,2025,https://iroapp.ir/archive/movies/per/2025/b/bi...,"[{'title': 'Drama', 'slug': 'drama', 'titleFar...",+15,4.8,4,1,1404/11/8,2026-01-28T21:27:25.094Z,2026-02-26T18:12:13.016976,2026-02-26T18:12:13.016985,2026-02-26T18:12:13.016994
61,25030,movies,otaghake-geli-2025,Otaghake Geli,اتاقک گِلی,2025,https://iroapp.ir/archive/movies/per/2025/o/ot...,"[{'title': 'Drama', 'slug': 'drama', 'titleFar...",+17,9.4,6,0,1404/11/8,2026-01-28T21:20:48.974Z,2026-02-26T18:12:13.017014,2026-02-26T18:12:13.017019,2026-02-26T18:12:13.017024
62,25029,movies,metri-6.5-2020,Metri 6.5,متری شیش و نیم,2020,https://iroapp.ir/archive/movies/per/2025/m/me...,"[{'title': 'Crime', 'slug': 'crime', 'titleFar...",+18,7.7,4,0,1404/11/8,2026-01-28T21:06:30.666Z,2026-02-26T18:12:13.017048,2026-02-26T18:12:13.017054,2026-02-26T18:12:13.017059
63,25028,movies,abado-yek-rooz-2017,Abado Yek Rooz,ابد و یک روز,2017,https://iroapp.ir/archive/movies/per/2025/a/ab...,"[{'title': 'Drama', 'slug': 'drama', 'titleFar...",+18,8.1,3,2,1404/11/8,2026-01-28T21:00:30.436Z,2026-02-26T18:12:13.017078,2026-02-26T18:12:13.017080,2026-02-26T18:12:13.017083
64,25023,movies,saddam-2026,Saddam,صددام,2026,https://iroapp.ir/archive/movies/per/2025/s/sa...,"[{'title': 'Comedy', 'slug': 'comedy', 'titleF...",,6.4,7,1,1404/11/8,2026-01-28T20:19:03.880Z,2026-02-26T18:12:13.017095,2026-02-26T18:12:13.017098,2026-02-26T18:12:13.017101

## 2. Data Preprocessing

In [8]:
# Create clean copy
df_clean = df.copy()

# Convert numeric columns
df_clean['imdbRating_numeric'] = pd.to_numeric(df['imdbRating'], errors='coerce').fillna(0)
df_clean['views_numeric'] = pd.to_numeric(df['views'], errors='coerce').fillna(0)
df_clean['likes_numeric'] = pd.to_numeric(df['likes'], errors='coerce').fillna(0)
df_clean['year_numeric'] = pd.to_numeric(df['year'], errors='coerce').fillna(2020)

# Fill missing genres
df_clean['genres'] = df_clean['genres'].apply(lambda x: x if isinstance(x, list) else [])
df_clean['englishTitle'] = df_clean['englishTitle'].fillna('Unknown')

# Extract genre list
def extract_genres(genres_list):
    if isinstance(genres_list, list):
        return [g.get('title', 'Unknown') for g in genres_list if isinstance(g, dict)]
    return []

df_clean['genre_list'] = df_clean['genres'].apply(extract_genres)

# Get unique genres
all_unique_genres = set()
for genres in df_clean['genre_list']:
    all_unique_genres.update(genres)
all_unique_genres = sorted(list(all_unique_genres))

print(f"Unique genres: {len(all_unique_genres)}")
print(f"Genres: {all_unique_genres[:10]}...")

Unique genres: 18
Genres: ['Action', 'Adventure', 'Animation', 'Biography', 'Comedy', 'Crime', 'Drama', 'Family', 'Fantasy', 'History']...

In [9]:
df_clean

,id,type,slug,englishTitle,alternateTitle,year,imageUrl,genres,rated,imdbRating,views,likes,updatedAt,updateTime,created_at,updated_at,processed_at,imdbRating_numeric,views_numeric,likes_numeric,year_numeric,genre_list
0,25114,movies,roshan-1398,Roshan,روشن,1398,https://iroapp.ir//archive/movies/per/1404/r/r...,"[{'title': 'Drama', 'slug': 'drama', 'titleFar...",+15,0,0,0,1404/12/7,2026-02-26T14:40:17.678Z,2026-02-26T18:12:13.015761,2026-02-26T18:12:13.015775,2026-02-26T18:12:13.015781,0.0,0,0,1398,[Drama]
1,25092,movies,shelter-2026,Shelter,Shelter,2026,https://iroapp.ir//archive/movies/english/s/sh...,"[{'title': 'Thriller', 'slug': 'thriller', 'ti...",N/A,0,0,1,1404/12/7,2026-02-26T14:40:07.170Z,2026-02-26T18:12:13.015819,2026-02-26T18:12:13.015826,2026-02-26T18:12:13.015832,0.0,0,1,2026,"[Thriller, Action]"
2,25113,movies,twisted-2026,Twisted,Twisted,2026,https://iroapp.ir//archive/movies/english/t/tw...,"[{'title': 'Horror', 'slug': 'horror', 'titleF...",R,4.6,0,0,1404/12/7,2026-02-26T14:33:35.357Z,2026-02-26T18:12:13.015860,2026-02-26T18:12:13.015864,2026-02-26T18:12:13.015869,4.6,0,0,2026,"[Horror, Thriller]"
3,25112,movies,firebreak-2026,Firebreak,Firebreak,2026,https://iroapp.ir//archive/movies/english/f/fi...,"[{'title': 'Drama', 'slug': 'drama', 'titleFar...",N/A,5.7,0,0,1404/12/7,2026-02-26T14:32:52.851Z,2026-02-26T18:12:13.015893,2026-02-26T18:12:13.015899,2026-02-26T18:12:13.015903,5.7,0,0,2026,"[Drama, Thriller]"
4,25111,movies,the-bluff-2025,The Bluff,The Bluff,2025,https://iroapp.ir//images/movie/t/the-bluff-20...,"[{'title': 'Drama', 'slug': 'drama', 'titleFar...",N/A,0,0,0,1404/12/7,2026-02-26T14:31:55.402Z,2026-02-26T18:12:13.015916,2026-02-26T18:12:13.015919,2026-02-26T18:12:13.015922,0.0,0,0,2025,"[Drama, Action, Adventure]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,25031,movies,bi-saro-seda-2024,Bi Saro Seda,بی سر و صدا,2025,https://iroapp.ir/archive/movies/per/2025/b/bi...,"[{'title': 'Drama', 'slug': 'drama', 'titleFar...",+15,4.8,4,1,1404/11/8,2026-01-28T21:27:25.094Z,2026-02-26T18:12:13.016976,2026-02-26T18:12:13.016985,2026-02-26T18:12:13.016994,4.8,4,1,2025,[Drama]
61,25030,movies,otaghake-geli-2025,Otaghake Geli,اتاقک گِلی,2025,https://iroapp.ir/archive/movies/per/2025/o/ot...,"[{'title': 'Drama', 'slug': 'drama', 'titleFar...",+17,9.4,6,0,1404/11/8,2026-01-28T21:20:48.974Z,2026-02-26T18:12:13.017014,2026-02-26T18:12:13.017019,2026-02-26T18:12:13.017024,9.4,6,0,2025,"[Drama, Action, War]"
62,25029,movies,metri-6.5-2020,Metri 6.5,متری شیش و نیم,2020,https://iroapp.ir/archive/movies/per/2025/m/me...,"[{'title': 'Crime', 'slug': 'crime', 'titleFar...",+18,7.7,4,0,1404/11/8,2026-01-28T21:06:30.666Z,2026-02-26T18:12:13.017048,2026-02-26T18:12:13.017054,2026-02-26T18:12:13.017059,7.7,4,0,2020,"[Crime, Action]"
63,25028,movies,abado-yek-rooz-2017,Abado Yek Rooz,ابد و یک روز,2017,https://iroapp.ir/archive/movies/per/2025/a/ab...,"[{'title': 'Drama', 'slug': 'drama', 'titleFar...",+18,8.1,3,2,1404/11/8,2026-01-28T21:00:30.436Z,2026-02-26T18:12:13.017078,2026-02-26T18:12:13.017080,2026-02-26T18:12:13.017083,8.1,3,2,2017,"[Drama, Family]"
64,25023,movies,saddam-2026,Saddam,صددام,2026,https://iroapp.ir/archive/movies/per/2025/s/sa...,"[{'title': 'Comedy', 'slug': 'comedy', 'titleF...",,6.4,7,1,1404/11/8,2026-01-28T20:19:03.880Z,2026-02-26T18:12:13.017095,2026-02-26T18:12:13.017098,2026-02-26T18:12:13.017101,6.4,7,1,2026,[Comedy]

## 3. Feature Engineering

In [ ]:
# Create genre one-hot encoding
for genre in all_unique_genres:
    df_clean[f'genre_{genre}'] = df_clean['genre_list'].apply(lambda x: 1 if genre in x else 0)

genre_cols = [col for col in df_clean.columns if col.startswith('genre_')]
print(f"Created {len(genre_cols)} genre features")

In [ ]:
# Create popularity score
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df_clean['views_norm'] = scaler.fit_transform(df_clean[['views_numeric']])
df_clean['likes_norm'] = scaler.fit_transform(df_clean[['likes_numeric']])
df_clean['popularity_score'] = 0.6 * df_clean['views_norm'] + 0.4 * df_clean['likes_norm']

# Scale numeric features
scaler = MinMaxScaler()
numeric_cols = ['imdbRating_numeric', 'year_numeric', 'popularity_score']
df_clean[numeric_cols] = scaler.fit_transform(df_clean[numeric_cols])

print("Features created successfully!")

## 4. Content-Based Filtering

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

# Build feature matrix
feature_cols = genre_cols + numeric_cols
feature_matrix = df_clean[feature_cols].values

print(f"Feature matrix: {feature_matrix.shape}")

# Compute similarity
similarity_matrix = cosine_similarity(feature_matrix)
print(f"Similarity matrix: {similarity_matrix.shape}")

In [ ]:
class ContentBasedRecommender:

    """Content-Based Filtering using cosine similarity"""
    

    def __init__(self, df, similarity_matrix):

        self.df = df

        self.similarity_matrix = similarity_matrix

        self.id_to_idx = {id_: idx for idx, id_ in enumerate(df['id'])}

    

    def get_similar_movies(self, movie_id, n=5):

        if movie_id not in self.id_to_idx:

            return None

        idx = self.id_to_idx[movie_id]

        sim_scores = self.similarity_matrix[idx]

        top_indices = np.argsort(sim_scores)[::-1][1:n+1]

        

        results = self.df.iloc[top_indices][['id', 'englishTitle', 'year', 'genre_list', 'imdbRating_numeric']].copy()

        results['similarity_score'] = sim_scores[top_indices]

        return results


content_recommender = ContentBasedRecommender(df_clean, similarity_matrix)
print("Content-Based Recommender ready!")

In [ ]:
# Test recommendations
sample_movie = df_clean.iloc[0]
print(f"Movie: {sample_movie['englishTitle']} ({sample_movie['year']})")
print(f"Genres: {sample_movie['genre_list']}")


recs = content_recommender.get_similar_movies(sample_movie['id'], n=5)

print("\nSimilar movies:")

print(recs[['englishTitle', 'year', 'similarity_score']].to_string(index=False))

## 5. Popularity-Based Recommender

In [ ]:
class PopularityRecommender:

    """Simple popularity-based recommender"""
    

    def __init__(self, df):

        self.df = df
    

    def get_top_rated(self, n=10):

        return self.df.nlargest(n, 'imdbRating_numeric')[['id', 'englishTitle', 'year', 'imdbRating_numeric', 'views_numeric', 'likes_numeric']]
    

    def get_most_viewed(self, n=10):

        return self.df.nlargest(n, 'views_numeric')[['id', 'englishTitle', 'year', 'views_numeric']]
    

    def get_most_liked(self, n=10):

        return self.df.nlargest(n, 'likes_numeric')[['id', 'englishTitle', 'year', 'likes_numeric']]


popularity_recommender = PopularityRecommender(df_clean)
print("Popularity Recommender ready!")
print("Top Rated Movies:")

print(popularity_recommender.get_top_rated(5).to_string(index=False))


print("\nMost Viewed:")
print(popularity_recommender.get_most_viewed(5).to_string(index=False))

## 6. Hybrid Recommender

In [ ]:
class HybridRecommender:

    """Combines content-based and popularity-based"""
    

    def __init__(self, df, similarity_matrix):

        self.df = df

        self.similarity_matrix = similarity_matrix

        self.id_to_idx = {id_: idx for idx, id_ in enumerate(df['id'])}
    

    def recommend(self, movie_id=None, liked_genres=None, n=10, content_weight=0.6, pop_weight=0.4):

        scores = np.zeros(len(self.df))

        

        if movie_id and movie_id in self.id_to_idx:

            idx = self.id_to_idx[movie_id]

            scores += content_weight * self.similarity_matrix[idx]
        

        if liked_genres:

            def genre_match(genres):

                return sum(1 for g in genres if g in liked_genres) / max(len(genres), 1)

            genre_scores = self.df['genre_list'].apply(genre_match).values

            scores += content_weight * 0.3 * genre_scores
        

        scores += pop_weight * self.df['popularity_score'].values
        

        top_indices = np.argsort(scores)[::-1][:n]

        results = self.df.iloc[top_indices][['id', 'englishTitle', 'year', 'genre_list']].copy()

        results['score'] = scores[top_indices]

        return results


hybrid_recommender = HybridRecommender(df_clean, similarity_matrix)
print("Hybrid Recommender ready!")

In [ ]:
# Test hybrid

pred = df_clean[df_clean['englishTitle'].str.contains('Predator', na=False)]

if len(pred) > 0:

    pred_id = pred['id'].iloc[0]

    print(f"User liked: {pred['englishTitle'].iloc[0]}")

    recs = hybrid_recommender.recommend(movie_id=pred_id, liked_genres=['Action'], n=5)

    print("\nHybrid recommendations:")

    print(recs.to_string(index=False))



print("\nGenre-based recommendations (Drama, Romance):")

recs = hybrid_recommender.recommend(liked_genres=['Drama', 'Romance'], n=5)

print(recs.to_string(index=False))

## 7. Evaluation

In [ ]:
import random


def evaluate_recommender(recommender, df, n_recommendations=10, n_users=15):

    """Evaluate based on genre overlap"""

    precisions = []

    recalls = []

    

    sample_indices = random.sample(range(len(df)), min(n_users, len(df)))

    

    for idx in sample_indices:

        movie = df.iloc[idx]

        genres = movie['genre_list']

        

        if not genres or not isinstance(genres, list):

            continue

        

        test_genres = set(genres)

        

        # Get recommendations

        if hasattr(recommender, 'get_similar_movies'):

            recs = recommender.get_similar_movies(movie['id'], n=n_recommendations)

        else:

            recs = recommender.recommend(movie_id=movie['id'], n=n_recommendations)

        

        if recs is None or len(recs) == 0:

            continue

        

        # Check genre overlap

        overlaps = []

        for _, row in recs.iterrows():

            rec_genres = row['genre_list']

            if isinstance(rec_genres, list):

                overlaps.append(len(test_genres & set(rec_genres)) > 0)

            else:

                overlaps.append(False)
        

        precision = sum(overlaps) / len(overlaps) if overlaps else 0

        recall = 1 if any(overlaps) else 0

        

        precisions.append(precision)

        recalls.append(recall)

    

    return {

        'precision': np.mean(precisions) if precisions else 0,

        'recall': np.mean(recalls) if recalls else 0

    }


print("Evaluating Content-Based...")

content_metrics = evaluate_recommender(content_recommender, df_clean)

print(f"Content-Based: {content_metrics}")


print("\nEvaluating Hybrid...")

hybrid_metrics = evaluate_recommender(hybrid_recommender, df_clean)

print(f"Hybrid: {hybrid_metrics}")

In [ ]:
# Visualize results

fig, ax = plt.subplots(figsize=(8, 5))

metrics = ['Precision', 'Recall']

content_scores = [content_metrics['precision'], content_metrics['recall']]

hybrid_scores = [hybrid_metrics['precision'], hybrid_metrics['recall']]



x = np.arange(len(metrics))

width = 0.35



ax.bar(x - width/2, content_scores, width, label='Content-Based', color='steelblue')

ax.bar(x + width/2, hybrid_scores, width, label='Hybrid', color='coral')

ax.set_ylabel('Score')

ax.set_title('Model Evaluation')

ax.set_xticks(x)

ax.set_xticklabels(metrics)

ax.legend()

ax.set_ylim(0, 1)

plt.tight_layout()

plt.show()

## 8. Summary

In [ ]:
print("="*50)

print("RECOMMENDER SYSTEM SUMMARY")

print("="*50)

print(f"""

Dataset:

  • Movies: {len(df_clean)}

  • Genres: {len(all_unique_genres)}

  • Year range: {df_clean['year_numeric'].min():.0f}-{df_clean['year_numeric'].max():.0f}



Features:

  • Genre one-hot: {len(genre_cols)}

  • Numeric: {len(numeric_cols)}

  • Total: {len(feature_cols)}



Models:

  1. Content-Based (cosine similarity)

  2. Popularity-Based (views, likes, ratings)

  3. Hybrid (content + popularity)



Results:

  • Content: Precision={content_metrics['precision']:.2f}, Recall={content_metrics['recall']:.2f}

  • Hybrid: Precision={hybrid_metrics['precision']:.2f}, Recall={hybrid_metrics['recall']:.2f}

""")